version: '2'
services:
  fastcgi:
    image: k8s-llng-fastcgi
    volumes:
      - dataavailable:/etc/nginx/sites-available
      - dataenabled:/etc/nginx/sites-enabled
      - fastcgisocket:/var/run/llng-fastcgi-server/llng-fastcgi.sock
  nginx:
    image: k8s-llng-nginx
    ports:
      - "80:8080"
    volumes:
      - dataavailable:/etc/nginx/sites-available
      - dataenabled:/etc/nginx/sites-enabled
      - fastcgisocket:/var/run/llng-fastcgi-server/llng-fastcgi.sock
volumes:
  dataenabled: {}
  dataavailable: {}
  fastcgisocket: {}
